export { default as Footer } from './Footer'
export { default as Icons } from './Icons'
export { default as MaxWidthWrapper } from './MaxWidthWrapper'
export { default as Navbar } from './Navbar'
export { default as Phone } from './Phone'
export { default as Reviews } from './Reviews'
